# Generated by Django 3.0.3 on 2020-03-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
