# Generated by Django 3.0.3 on 2020-03-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20200308_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='in_cart',
        ),
        migrations.RemoveField(
            model_name='order_products',
            name='in_cart',
        ),
    ]
